#!/usr/bin/env bash
# Per-project volume mount management for devbox.
#
# Stores mounts as a Docker Compose override file that gets merged via
# _compose_file_args(). Mounts take effect on next container start.
#
# Security: the override YAML is generated (never user-edited) and contains
# ONLY volume directives. _compose_file_args() validates structure before use.
set -euo pipefail

# Container paths reserved by devbox — user mounts must not conflict.
_BLOCKED_CONTAINER_PATHS=(
    /workspace
    /devbox
    /home/devbox
    /run/proxy-ca
    /data
    /tmp
    /etc
    /opt
    /var
    /run
    /proc
    /sys
    /dev
    /root
)

# Host paths that should not be mounted into containers.
_BLOCKED_HOST_PATHS=(
    "${HOME}/.ssh"
    "${HOME}/.gnupg"
    "${HOME}/.aws"
    "${HOME}/.kube"
    "${HOME}/.docker"
    "${HOME}/.devbox/secrets"
    /etc/shadow
    /etc/passwd
    /etc/sudoers
)

# Resolve a project name or cwd to a compose override file path.
_mount_override_file() {
    local name="${1:-}"
    local hash
    if [ -n "$name" ]; then
        hash="$(_hash_for_project_name "$name")" || {
            local path
            path="$(resolve_project_path "$name")" || return 1
            hash="$(project_hash "$path")"
        }
    else
        local path
        path="$(resolve_project_path)"
        hash="$(project_hash "$path")"
    fi
    echo "${DEVBOX_DATA}/${hash}/compose.override.yml"
}

# Parse existing mounts from a compose override file.
# Outputs lines in the format stored in YAML: host_path:container_path:mode
_parse_mounts() {
    local file="$1"
    [ -f "$file" ] || return 0
    # Extract volume strings from YAML (between double quotes on volume lines).
    grep '^\s*- ' "$file" | sed "s/^[[:space:]]*- ['\"]//; s/['\"]$//" | while IFS= read -r line; do
        echo "$line"
    done
}

# Write mounts array to compose override YAML.
# SECURITY: only generates volume directives — no other compose keys.
_write_compose_override() {
    local file="$1"
    shift
    local -a mounts=("$@")

    if [ ${#mounts[@]} -eq 0 ]; then
        rm -f "$file"
        return 0
    fi

    (
        umask 077
        {
            echo "# Auto-generated by devbox mount. Do not edit directly."
            echo "services:"
            echo "  agent:"
            echo "    volumes:"
            for m in "${mounts[@]}"; do
                # Single-quote the YAML string to prevent injection.
                echo "      - '${m}'"
            done
        } > "$file"
    )
}

# Validate the compose override file structure before Docker Compose uses it.
# Rejects files with anything other than volume directives.
_validate_compose_override() {
    local file="$1"
    [ -f "$file" ] || return 0
    # Only allow: comments, "services:", "  agent:", "    volumes:", and volume entries.
    if grep -qvE '^\s*#|^services:\s*$|^\s+agent:\s*$|^\s+volumes:\s*$|^\s+- .|^\s*$' "$file"; then
        ui_error "Compose override contains unexpected directives: $file"
        ui_error "Only volume mounts are allowed. Regenerate with: devbox mount add"
        return 1
    fi
}

# Validate mount paths.
_validate_mount_paths() {
    local host_path="$1"
    local container_path="$2"

    # Host path must exist.
    if [ ! -d "$host_path" ]; then
        ui_error "Host path does not exist: $host_path"
        return 1
    fi

    # Container path must be absolute.
    if [[ "$container_path" != /* ]]; then
        ui_error "Container path must be absolute: $container_path"
        return 1
    fi

    # Reject paths with special characters that could break YAML or parsing.
    if [[ "$host_path" == *\'* ]] || [[ "$container_path" == *\'* ]]; then
        ui_error "Paths must not contain single quotes."
        return 1
    fi
    if [[ "$host_path" == *$'\n'* ]] || [[ "$container_path" == *$'\n'* ]]; then
        ui_error "Paths must not contain newlines."
        return 1
    fi

    # Check blocked container paths.
    local blocked
    for blocked in "${_BLOCKED_CONTAINER_PATHS[@]}"; do
        if [ "$container_path" = "$blocked" ] || [[ "$container_path" == "${blocked}/"* ]]; then
            ui_error "Cannot mount to $container_path — reserved by devbox."
            return 1
        fi
    done

    # Host path must be under $HOME — prevents mounting /, /etc, /Users, etc.
    # This is an allowlist approach: only the user's own directories are eligible.
    local resolved_host
    resolved_host="$(cd "$host_path" && pwd -P)"
    if [[ "$resolved_host" != "${HOME}/"* ]] && [ "$resolved_host" != "$HOME" ]; then
        ui_error "Host path must be under your home directory ($HOME)."
        ui_error "Got: $resolved_host"
        return 1
    fi

    # Check blocked host paths within $HOME.
    local blocked
    for blocked in "${_BLOCKED_HOST_PATHS[@]}"; do
        if [ "$resolved_host" = "$blocked" ] || [[ "$resolved_host" == "${blocked}/"* ]]; then
            ui_error "Cannot mount $resolved_host — contains sensitive data."
            return 1
        fi
    done
}

# Add a mount to a project.
mount_add() {
    local file="$1"
    local host_path="$2"
    local container_path="$3"
    local mode="${4:-rw}"

    # Validate mode.
    if [ "$mode" != "rw" ] && [ "$mode" != "ro" ]; then
        ui_error "Mount mode must be 'rw' or 'ro', got: $mode"
        return 1
    fi

    # Resolve host path to absolute.
    host_path="$(cd "$host_path" && pwd)"

    _validate_mount_paths "$host_path" "$container_path" || return 1

    # Check for duplicate container path.
    local -a existing=()
    while IFS= read -r line; do
        [ -n "$line" ] && existing+=("$line")
    done < <(_parse_mounts "$file")

    # Extract container path — it's the second colon-delimited field.
    # Host paths are absolute (start with /), container paths are absolute (start with /),
    # so the format is always: /abs/host:/abs/container:mode
    for m in "${existing[@]+"${existing[@]}"}"; do
        local cp
        # Remove host path prefix (everything up to and including the second /)
        # by splitting on the pattern /:/ which separates host:container.
        cp="$(echo "$m" | sed 's|^[^:]*:||; s|:[^:]*$||')"
        if [ "$cp" = "$container_path" ]; then
            ui_error "Mount already exists at $container_path. Remove it first."
            return 1
        fi
    done

    existing+=("${host_path}:${container_path}:${mode}")
    _write_compose_override "$file" "${existing[@]}"
    ui_info "Added mount: ${host_path} → ${container_path} (${mode})"
    ui_info "Restart the session for changes to take effect."
}

# Remove a mount by container path.
mount_remove() {
    local file="$1"
    local container_path="$2"

    if [ ! -f "$file" ]; then
        ui_info "No custom mounts configured."
        return 0
    fi

    local -a remaining=()
    local found=false
    while IFS= read -r line; do
        [ -z "$line" ] && continue
        local cp
        cp="$(echo "$line" | sed 's|^[^:]*:||; s|:[^:]*$||')"
        if [ "$cp" = "$container_path" ]; then
            found=true
        else
            remaining+=("$line")
        fi
    done < <(_parse_mounts "$file")

    if [ "$found" = false ]; then
        ui_error "No mount found at $container_path"
        return 1
    fi

    _write_compose_override "$file" "${remaining[@]+"${remaining[@]}"}"
    ui_info "Removed mount at $container_path"
    ui_info "Restart the session for changes to take effect."
}

# List mounts for a project.
mount_list() {
    local file="$1"

    if [ ! -f "$file" ]; then
        ui_info "No custom mounts configured."
        return 0
    fi

    local count=0
    while IFS= read -r line; do
        [ -z "$line" ] && continue
        local hp cp mode
        # Parse: /host/path:/container/path:mode
        hp="$(echo "$line" | sed 's|:[^:]*:[^:]*$||')"
        cp="$(echo "$line" | sed 's|^[^:]*:||; s|:[^:]*$||')"
        mode="$(echo "$line" | sed 's|^.*:||')"
        hp="${hp/#$HOME/\~}"
        echo "  ${hp} → ${cp} (${mode})"
        count=$((count + 1))
    done < <(_parse_mounts "$file")

    if [ "$count" -eq 0 ]; then
        ui_info "No custom mounts configured."
    fi
}
